name: Go Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm64
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: arm64
          - goos: darwin
            goarch: amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: |
          echo "Building for ${{ matrix.goos }} ${{ matrix.goarch }}"
          suffix=""
          if [ "${{ matrix.goos }}" == "windows" ]; then
            suffix=".exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./build/gpt-${{ matrix.goos }}-${{ matrix.goarch }}$suffix

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gpt-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./build/gpt-${{ matrix.goos }}-${{ matrix.goarch }}*

